### ISSUE TITLE
Use the new Framework API?

### ISSUE THREAD

**Issue by slorber** [jodyheavener/storybook-addon-docusaurus#1]
Hey 👋 

https://storybook.js.org/blog/framework-api/

I thought it might be relevant for this addon? 🤔

**Comment by jodyheavener** [comment]
I'll take a peak and see how it fits into this plugin!

**Comment by jodyheavener** [comment]
Have this mostly working here: https://github.com/jodyheavener/storybook-addon-docusaurus/compare/sb7-framework

Will package it up soon for preview release.

**Comment by jodyheavener** [comment]
[Done](https://github.com/jodyheavener/storybook-docusaurus/tree/main/framework) and [published](https://www.npmjs.com/package/storybook-framework-docusaurus)! Still a WIP but overall I like this better than the addon.
